### ISSUE TITLE
"libstdc++.so.6: version `GLIBCXX_3.4.21' not found" on Raspbian Jessie

### ISSUE THREAD

**Issue by teedeepee** [doublethinkco/cpp-ethereum-cross#79] opened 2016-03-19 16:39 UTC
Hi, this may be related to #71. On a fresh, up-to-date Raspbian Jessie install running on a Raspberry Pi 2, starting eth returns the error:

```
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./eth)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libdevcore.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libdevcrypto.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libp2p.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libethcore.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libethereum.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libjsonrpccpp-common.so.0)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libjsonrpccpp-client.so.0)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libjsonrpccpp-server.so.0)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libweb3jsonrpc.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libwebthree.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libethashseal.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libleveldb.so.1)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libevm.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/liblll.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libevmcore.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libwhisper.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libethash.so)
./eth: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pi/eth/lib/libevmasm.so)
```

apt-get tells me that libstdc++.so.6 is up to date. Any suggestion?

**Comment by bobsummerwill** [comment] 2016-03-20 00:22
Hey, @teedeepee!

Thanks for the report.   Yes, it will be another manifestation of the same issue.    https://github.com/doublethinkco/cpp-ethereum-cross/issues/72 is the real root cause.    The GCC version on the host machine used for the cross-builds ends up mapping 1-1 to the GLIBC version needed on the target machine to be able to run the generated executables.

For the ARMv5 binaries that is currently GCC 4.9, which works on most devices.
For the ARMv7 binaries I am building them on Ubuntu Wily, which has GCC 5.3.

So you **should** be able to resolve this on your device by installing the latest GCC, if that is available?   That has the side-effect of updating your global GLIBC SO files.

This detail is another level-of-hell on top of ARM ABI stuff which I worked through just prior to writing http://doublethink.co/2015/12/31/a-tale-of-two-abis/.

When I finally fix this one, I'll write another blog article, to try to empty my brain of the horror.

Let me know if you successfully work around this.     Aside, if you use https://github.com/doublethinkco/cpp-ethereum-cross/releases/download/v1.2.2/crosseth-armhf-v1.2.2.tgz (ARMv5) rather than https://github.com/doublethinkco/cpp-ethereum-cross/releases/download/v1.2.2/crosseth-armhf-apt-v1.2.2.tgz (ARMv7) it might "just work", though the binary will be suboptimal.

Thanks again for the report.   I've added this to my milestone, so I ensure to check back.

**Comment by teedeepee** [comment] 2016-03-21 19:07
Hi @bobsummerwill,

Thank you so much for your detailed reply. I upgraded to GCC-5 and was able to at least launch `eth`, though I soon run into a fatal error:

`*** Error in `./eth': corrupted double-linked list: 0x016a2988 ***`

Here's what I did, for the record:

1. Edit the package source file with `sudo nano /etc/apt/sources.list`
2. Replace `jessie` with `stretch` in that file to point to the testing repository that has the [gcc-5 package](https://packages.debian.org/stretch/gcc-5)
3. `sudo apt-get update` to refresh the list of packages
4. `sudo apt-get install gcc-5` to install v5.3.1-11 (at time of writing) of the compiler
5. Run `./eth` again

**Comment by bobsummerwill** [comment] 2016-03-21 19:10
Great - some progress!

Please could you try running eth again under gdb, and see whether we can get a call stack out of it?

That corrupted double-linked list error does ring a bell.    I think we saw that before at some point on one of the platforms, though it utterly escapes me which one!    Maybe with a little more poking here we can get past that too.

**Comment by teedeepee** [comment] 2016-03-21 19:39
Well, I'm totally confused now - I did a `sudo reboot`, re-declared `export LD_LIBRARY_PATH=~/eth/lib `, ran `eth` again, and somehow it is running fine and syncing blocks. Total voodoo. Anyway, thank you so much for your help @bobsummerwill, upgrading gcc was the answer!

**Comment by bobsummerwill** [comment] 2016-03-21 19:48
Awesome!    We'll take it, eh?   Ha ha.

So I'll close this issue now, because we won't be able to replicate the issue on your Pi 2 anymore unless you uninstall GCC 5.3.

We can be pretty confident that if we build the binary against older GLIBC runtime that it will work, so I will assume that a fix for the other issues is a fix for this one.

Thanks for the report.   Glad you have it work.     Are you syncing the block-chain now?    Please do let me know how long the sync takes.    For many lower-power devices this seems to take DAYS right now.    Hence my pending focus on Light Client :-)

**Closed by bobsummerwill** 2016-03-21 19:48 UTC
Labels: bug

**Comment by teedeepee** [comment] 2016-03-22 16:57
Hi @bobsummerwill! So after 21 or so hours, the Pi is importing block number 180,850. There are 1,197,580 blocks in the chain as I write, so it'll take a total of 139 hours, or about 5.7 days to catch up; though in that timeframe, at a rate of 1 block every 14.3 seconds according to etherchain.org, 35,000 more blocks will be added, which will bring me just over the 6 days mark to sync the whole chain.

**Comment by bobsummerwill** [comment] 2016-03-22 23:31
Ha ha!

I think we worked out for the Raspberry Pi that it would take several months to catch up, because it could only just keep pace with new block creation.

Now you see why me getting on to actually doing Light Client for C++ is so important!

Best wishes.

**Comment by straytachyon** [comment] 2017-03-18 02:59
An up-to-date raspbian on raspberry pi 2.  Installing gcc (gcc-4.9 (4.9.2-10)) doesn't help

57302227 Mar 17 20:16 dotnet-ubuntu.16.04-arm.latest.tar.gz

dotnet failed with the following message

dotnet: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ms/dotnet)

strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by bobsummerwill** [comment] 2017-03-18 03:14
@straytachyon Not sure why you added the detail about "dotnet" issue here?

But I believe that your error message indicates that you need to install GCC 5.0 or newer to be able to run dotnet on your Pi2 (because it was compiled with GCC 5.0 so needs libstdc++ from GCC 5.0 or newer).

**Comment by straytachyon** [comment] 2017-03-18 03:57
sorry, only took a brief look at the previous post and thought it's a similar issue :)
my bad

Thanks for the pointer

**Comment by bobsummerwill** [comment] 2017-03-18 05:17
np, @straytachyon.  Good luck!

**Comment by jixiedaima** [comment] 2017-03-20 08:07
@straytachyon ,I met the same error,how do you solve it?

**Comment by straytachyon** [comment] 2017-03-20 19:55
Hi Shengguang, just following the instructions from teedeepee comments from Mar 21, 2016:

Edit the package source file with sudo nano /etc/apt/sources.list
Replace jessie with stretch in that file to point to the testing repository that has the gcc-5 package
sudo apt-get update to refresh the list of packages
sudo apt-get install gcc-5

A lot of packages will be updated.  However, stretch is still in testing so there might be instability problems
